# Generated by Django 3.1.2 on 2020-10-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'memories'},
        ),
    ]
