# Generated by Django 3.1.2 on 2020-10-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0002_auto_20201014_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='memory',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='places_remember.memory'),
            preserve_default=False,
        ),
    ]
